"""Deterministic provider used for tests and runs without API keys."""

from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel

from ai_team.agents.contracts import (
    ArchitectProposal,
    CoderOutput,
    DebateProposal,
    FileChange,
    FailureScenario,
    JudgeOutput,
    ManagerDecision,
    ManagerPlan,
    RedTeamOutput,
    ResearchFinding,
    ReviewerOutput,
)
from ai_team.models.base import ChatMessage, GenerateResult, ModelProvider


class MockProvider(ModelProvider):
    name = "mock"

    async def generate(
        self,
        messages: list[ChatMessage],
        *,
        response_schema: type[BaseModel] | None = None,
        temperature: float = 0.2,
    ) -> GenerateResult:
        user = next((m.content for m in reversed(messages) if m.role == "user"), "")
        payload = _mock_payload(response_schema, user)
        text = json.dumps(payload)
        parsed = response_schema.model_validate(payload) if response_schema else None
        return GenerateResult(text=text, parsed=parsed, tokens_in=len(user) // 4, tokens_out=len(text) // 4)


def _task_slug(user: str) -> str:
    lowered = user.lower()
    if "auth" in lowered:
        return "auth"
    if "redis" in lowered or "rabbit" in lowered:
        return "queue"
    return "feature"


def _mock_payload(schema: type[BaseModel] | None, user: str) -> dict[str, Any]:
    slug = _task_slug(user)
    if schema is ManagerPlan:
        return ManagerPlan(
            understanding=f"User asked: {user[:240]}",
            tasks=[f"Design {slug}", f"Implement {slug}", f"Review {slug}"],
            chosen_agents=["architect", "researcher", "coder", "reviewer", "redteam"],
            questions=[],
            risks=["Scope may be larger than expected"],
            next_action="Collect specialist proposals",
        ).model_dump()
    if schema is ManagerDecision:
        return ManagerDecision(
            decision=f"Proceed with a simple {slug} design",
            approved=True,
            confidence=0.78,
            reason="Specialists agree on a small, testable first slice.",
            rejected_alternatives=["Big-bang rewrite"],
            remaining_risks=["Edge cases remain"],
            follow_up="Delegate implementation to Coder",
        ).model_dump()
    if schema is ArchitectProposal:
        return ArchitectProposal(
            summary=f"Keep {slug} modular and testable.",
            architecture="Small module with a clear interface and unit tests.",
            technology_choices=["Python", "pytest"],
            trade_offs=["Simplicity over premature scale"],
            alternatives=["Distributed service"],
            risks=["Hidden coupling"],
            recommended_option="In-process module first",
        ).model_dump()
    if schema is ResearchFinding:
        return ResearchFinding(
            topic=slug,
            findings=["Start with the smallest working slice.", "Prefer existing libraries."],
            options=["Build in-process", "Extract a service later"],
            recommendation="Build in-process first",
            evidence=["Operational complexity of extra infra is high for V1."],
            uncertainties=["Future load is unknown"],
        ).model_dump()
    if schema is CoderOutput:
        src = f"src/{slug}.py"
        test = f"tests/test_{slug}.py"
        return CoderOutput(
            task=f"Implement {slug}",
            changes=[
                FileChange(
                    path=src,
                    action="create",
                    content=(
                        f'"""Minimal {slug} module generated by AI-Team mock coder."""\n\n'
                        "def ping() -> str:\n"
                        '    return "ok"\n'
                    ),
                    reason="Provide a testable entry point",
                ),
                FileChange(
                    path=test,
                    action="create",
                    content=(
                        "import sys\n"
                        "from pathlib import Path\n\n"
                        "sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'src'))\n\n"
                        f"from {slug} import ping\n\n\n"
                        "def test_ping() -> None:\n"
                        '    assert ping() == "ok"\n'
                    ),
                    reason="Lock the happy path",
                ),
            ],
            files_modified=[src, test],
            reasoning_summary="Ship a tiny, tested module as the first slice.",
            tests=[f"python -m pytest {test} -q -c /dev/null"],
            risks=["Placeholder logic only"],
            needs_approval=True,
        ).model_dump()
    if schema is ReviewerOutput:
        return ReviewerOutput(
            verdict="approve",
            critical_issues=[],
            major_issues=[],
            minor_issues=["Placeholder implementation is intentionally small"],
            security_issues=[],
            required_changes=[],
            summary="Safe to commit as an initial slice.",
        ).model_dump()
    if schema is RedTeamOutput:
        return RedTeamOutput(
            attack_surface=["Public function API"],
            assumptions=["Callers only need a ping health check"],
            failure_scenarios=[
                FailureScenario(
                    name="Missing real business logic",
                    description="The module is a stub and will not satisfy production auth/queue needs.",
                    severity="medium",
                    exploitability="low",
                )
            ],
            severity="medium",
            exploitability="low",
            mitigation=["Replace stub with real logic in the next task"],
            should_block=False,
        ).model_dump()
    if schema is DebateProposal:
        position = "In-process first"
        if "redis" in user.lower():
            position = "Redis for cache, not as the only queue"
        return DebateProposal(
            agent="specialist",
            position=position,
            arguments=["Lower operational cost", "Fits current project constraints"],
            counterarguments=["May need to extract later"],
            evidence=["V1 success criteria prefer stability over scale"],
        ).model_dump()
    if schema is JudgeOutput:
        return JudgeOutput(
            decision="Choose the simpler in-process option for V1",
            confidence=0.8,
            reason="Evidence and project constraints favor simplicity.",
            rejected_alternatives=["Introduce extra infrastructure now"],
            remaining_risks=["Will need to revisit if load grows"],
            scores={
                "correctness": 0.8,
                "evidence": 0.7,
                "project_compatibility": 0.9,
                "complexity": 0.85,
                "cost": 0.9,
                "security": 0.7,
                "maintainability": 0.8,
                "risks": 0.7,
            },
        ).model_dump()
    return {"result": f"mock response for: {user[:200]}"}
